sudo: false

language: bash
script:
- echo YOLO straight to prod
deploy:
  provider: s3
  access_key_id: AKIAJGMDPBO6WAJAZRQA
  secret_access_key:
    secure: PhgNSq4p7GSl9tK1pu4REw00gNpPeki7D6MHu9VIqMd1KaJfpFqZ4+OzntAWSWTNBvDSZpzqT+oR4ALAg/31o9dYegnOk7JiobHNlgFWFa8YECcMwje1aTbMaeAQ5ZQBzgikaDXdfzuJPwK8frrcSvvJjldNFpnE52WZ4BcfM4TtsZNYPMYgKKip77g1ba/f/hguXESZp/9bWB0tCQLY7aLpxhx/QQLQYncF5IgtGkEO1UNJYZdPdcHvozyzEw9EhDm/jMGe/2UIkpao/koX0tsfH6JKO+Fz1qeUFtQyRUNEJeoEJwSLPDEBOevRF5QW+WSO/vt7MiMhWB2J12Fif52xLPEtIhgzSOsvgvGX777FF/i87Gv5UshUXv2SlJyCJ1tKmuwkh1vrY7fz9DwW4kyomYwnmU3Ce4m46M151pmf/YEx9n4CeXIdutU26iOHT9XIa2sIxh5iTrZUcPudGuaO7cAfe89874+kyh3prk4CuNFVgD3rB6J4xEv8FV8OdFirBDhXTKUf+SR9az3vpT2Ox0aYIdZU5+UuMOZbHzIjrEIS6Gs5DVBmkvX3ITlkNupcUaY8Y2YmTcC7QVXGZ0oNI1OIPaoDeEF0em0XCn1S42aLnlh74M3K2iwpQBcTY2NBYa04Z9LORAUi/QGYnl0Te1ZbYfq3sZ95Bb14zbQ=
  bucket: tirefi.re
  acl: public_read
  on:
    repo: moutons/tirefi.re
